### ISSUE TITLE
Missing words.txt test file used in tests

### ISSUE THREAD

**Issue by quipo** [AndreasBriese/bloom#1]
missing from both repos:

https://github.com/AndreasBriese/bloom/blob/master/bloom_test.go#L78
https://github.com/AndreasBriese/bbloom/blob/master/bbloom_test.go#L18

**Comment by AndreasBriese** [comment]
Hey,

you may use any textfile containing about a million different lines to conduct the test (rename the file words.txt) or you use permut.py from the repo https://github.com/AndreasBriese/bloom to create world.txt as indicated in the README file:

see: read me/test
...  use create wordlist in file "words.txt" (you might use python permut.py)

**Comment by quipo** [comment]
sorry, missed that paragraph in the README.  Thanks!

**Comment by AndreasBriese** [comment]
Anyway - i would recommend using bbloom instead of bloom since it is dramatically faster.
If scared about package unsafe you might consider refactoring the code for bit access by the equivalent function in the math/big package  (https://golang.org/pkg/math/big/#Int.Bit)

Have fun

Andreas


Am 23.01.2017 um 12:29 schrieb Lorenzo Alberton <notifications@github.com>:

**Comment by AndreasBriese** [comment]
…. or use []float64 instead of uint64 and https://golang.org/pkg/math/#Float64bits  && https://golang.org/pkg/math/#Float64frombits  to access the individual bits
...

**Comment by quipo** [comment]
Is it faster though? I ran a quick benchmark with a words.txt file of 10K GUIDs (go1.8beta2 darwin/amd64):

```
bloom$ go test -v -run XXX -bench .
BenchmarkM_New-8   	    5000	    244665 ns/op	 1048624 B/op	       2 allocs/op
BenchmarkM_Add-8   	     500	   3258154 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_Has-8   	     500	   3651150 ns/op	       0 B/op	       0 allocs/op
```
```
bbloom$ go test -v -run XXX -bench .
BenchmarkM_New-8                      	   50000	     34278 ns/op	  131072 B/op	       1 allocs/op
BenchmarkM_Clear-8                    	  300000	      5702 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_Add-8                      	     300	   4050529 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_Has-8                      	     300	   4320159 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_AddIfNotHasFALSE-8         	     300	   4752736 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_AddIfNotHasClearTRUE-8     	     300	   5397046 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_AddTS-8                    	     200	   9522272 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_HasTS-8                    	     200	   9779275 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_AddIfNotHasTSFALSE-8       	     100	  10303890 ns/op	       0 B/op	       0 allocs/op
BenchmarkM_AddIfNotHasTSClearTRUE-8   	     100	  10904397 ns/op	       0 B/op	       0 allocs/op
````
